# Installation
Du behöver venv och pip install -r requirements.txt som står i den andra notebook-filen

In [13]:
import pandas as pd

df = pd.read_excel("Artikellistan2024.xlsx", header=4)

In [14]:
# Vi extraherar siffervärdet för alkoholprocenten
# från kvittonamn med regex
alc_regex = r"\b(\d{1,2}(?:[.,]\d{1,2})?\s?)%"
df["Alkoholhalt"] = df["Kvittonamn"].str.extract(alc_regex)

# eftersom vi i Sverige har , istället för .
# omvandlar vi detta med str.replace så att vi kan
# göra en float av värdet

df["Alkoholhalt"] = df["Alkoholhalt"].str.replace(',', '.')
df["Alkoholhalt"] = df["Alkoholhalt"].astype(float)
df

,Artnr,Varunr,Kvittonamn,Namn,Producentnamn,Varugrupp,Varugrupp detalj,Rubrik,Aktuellt pris,Volym i ml,Buteljtyp,Land,Region,Ursprung,Ekologisk,Etiskt,Försäljning i liter,Artikel ID,Alkoholhalt
0,101,1,"Renat 37,5% 700 ml",Renat,Pernod Ricard,Sprit,Drinkar & Cocktails,VODKA,215.0,700,Helbutelj,Sverige,Sverige,Sverige,NaN,NaN,180079.90,1,37.5
1,102,1,"Renat 37,5% 350 ml",Renat,Pernod Ricard,Sprit,Drinkar & Cocktails,VODKA,115.0,350,Halvbutelj,Internationellt märke,Internationellt märke,Internationellt märke,NaN,NaN,60997.30,2,37.5
2,302,3,"Explorer Vodka 37,5% 350 ml",Explorer Vodka,Altia Sweden AB,Sprit,Drinkar & Cocktails,VODKA,108.0,350,Halvbutelj,Internationellt märke,Internationellt märke,Internationellt märke,NaN,NaN,4.55,8,37.5
3,401,4,Kronvodka 40% 700 ml,Kronvodka,Altia,Sprit,Drinkar & Cocktails,VODKA,246.0,700,Helbutelj,Internationellt märke,Internationellt märke,Internationellt märke,NaN,NaN,115297.00,11,40.0
4,402,4,Kronvodka 40% 350 ml,Kronvodka,Altia,Sprit,Drinkar & Cocktails,VODKA,130.0,350,Halvbutelj,Internationellt märke,Internationellt märke,Internationellt märke,NaN,NaN,4436.60,12,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46594,60007501,600075,PET ME BABY ONE MORE TIME,PET ME BABY ONE MORE TIME,Okänd producent,NaN,NaN,NaN,79.0,750,Helbutelj,NaN,NaN,NaN,NaN,NaN,112.50,52176972,NaN
46595,60018701,600187,Txomin Etxaniz Blanco,Txomin Etxaniz Blanco,Okänd producent,NaN,NaN,NaN,217.0,750,Helbutelj,NaN,NaN,NaN,NaN,NaN,4.50,52177064,NaN
46596,66696802,666968,Shun Tun,Shun Tun,Okänd producent,NaN,NaN,NaN,406.0,500,Halvlitersbutelj,NaN,NaN,NaN,NaN,NaN,0.50,52265814,NaN
46597,60098802,600988,Guy Charlemagne,Guy Charlemagne,Okänd producent,NaN,NaN,NaN,341.0,375,Halvbutelj,NaN,NaN,NaN,NaN,NaN,0.75,52266067,NaN
46598,60102901,601029,Jubeleums Champagne 2016,Jubeleums Champagne 2016,Okänd producent,NaN,NaN,NaN,652.0,750,Helbutelj,NaN,NaN,NaN,NaN,NaN,1.50,52266081,NaN

In [15]:
# Vi vill filtrera bort allt som saknar alkoholhalt

df = df[df["Alkoholhalt"] > 0]
df

,Artnr,Varunr,Kvittonamn,Namn,Producentnamn,Varugrupp,Varugrupp detalj,Rubrik,Aktuellt pris,Volym i ml,Buteljtyp,Land,Region,Ursprung,Ekologisk,Etiskt,Försäljning i liter,Artikel ID,Alkoholhalt
0,101,1,"Renat 37,5% 700 ml",Renat,Pernod Ricard,Sprit,Drinkar & Cocktails,VODKA,215.0,700,Helbutelj,Sverige,Sverige,Sverige,NaN,NaN,180079.90,1,37.5
1,102,1,"Renat 37,5% 350 ml",Renat,Pernod Ricard,Sprit,Drinkar & Cocktails,VODKA,115.0,350,Halvbutelj,Internationellt märke,Internationellt märke,Internationellt märke,NaN,NaN,60997.30,2,37.5
2,302,3,"Explorer Vodka 37,5% 350 ml",Explorer Vodka,Altia Sweden AB,Sprit,Drinkar & Cocktails,VODKA,108.0,350,Halvbutelj,Internationellt märke,Internationellt märke,Internationellt märke,NaN,NaN,4.55,8,37.5
3,401,4,Kronvodka 40% 700 ml,Kronvodka,Altia,Sprit,Drinkar & Cocktails,VODKA,246.0,700,Helbutelj,Internationellt märke,Internationellt märke,Internationellt märke,NaN,NaN,115297.00,11,40.0
4,402,4,Kronvodka 40% 350 ml,Kronvodka,Altia,Sprit,Drinkar & Cocktails,VODKA,130.0,350,Halvbutelj,Internationellt märke,Internationellt märke,Internationellt märke,NaN,NaN,4436.60,12,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45876,60486703,604867,"Ability Shipping Starköl 5,5%","Ability Shipping Starköl 5,5%",Okänd producent,NaN,NaN,NaN,28.9,330,Flaska,NaN,NaN,NaN,NaN,NaN,79.20,51781636,5.5
45877,60498003,604980,"Ability Shipping Starköl 7,5%","Ability Shipping Starköl 7,5%",Okänd producent,NaN,NaN,NaN,29.9,330,Flaska,NaN,NaN,NaN,NaN,NaN,79.20,51781643,7.5
46184,60816001,608160,Ron Quorhum 30YO Anniversario 40%,Ron Quorhum 30YO Anniversario 40%,Okänd producent,NaN,NaN,NaN,999.0,700,Helbutelj,NaN,NaN,NaN,NaN,NaN,0.70,51875904,40.0
46380,60524802,605248,Het Snö (Spritglögg 35%vol),Het Snö (Spritglögg 35%vol),Okänd producent,NaN,NaN,NaN,278.0,500,Halvlitersbutelj,NaN,NaN,NaN,NaN,NaN,1.00,51883034,35.0
46400,8459801,84598,Daftmill Winter 2024 46% 700ml,Daftmill Winter Release 2024,Daftmill Distillery,Sprit,Whisky,MALTWHISKY,1722.0,700,Helbutelj,Storbritannien,Skottland,Lowlands,NaN,NaN,1.40,52033170,46.0

In [16]:
# ändra volym i ml till volym i liter för enklare beräkning
df = df.rename(columns={"Volym i ml": "Volym i liter"})
df["Volym i liter"] = df["Volym i liter"] / 1000
df

,Artnr,Varunr,Kvittonamn,Namn,Producentnamn,Varugrupp,Varugrupp detalj,Rubrik,Aktuellt pris,Volym i liter,Buteljtyp,Land,Region,Ursprung,Ekologisk,Etiskt,Försäljning i liter,Artikel ID,Alkoholhalt
0,101,1,"Renat 37,5% 700 ml",Renat,Pernod Ricard,Sprit,Drinkar & Cocktails,VODKA,215.0,0.70,Helbutelj,Sverige,Sverige,Sverige,NaN,NaN,180079.90,1,37.5
1,102,1,"Renat 37,5% 350 ml",Renat,Pernod Ricard,Sprit,Drinkar & Cocktails,VODKA,115.0,0.35,Halvbutelj,Internationellt märke,Internationellt märke,Internationellt märke,NaN,NaN,60997.30,2,37.5
2,302,3,"Explorer Vodka 37,5% 350 ml",Explorer Vodka,Altia Sweden AB,Sprit,Drinkar & Cocktails,VODKA,108.0,0.35,Halvbutelj,Internationellt märke,Internationellt märke,Internationellt märke,NaN,NaN,4.55,8,37.5
3,401,4,Kronvodka 40% 700 ml,Kronvodka,Altia,Sprit,Drinkar & Cocktails,VODKA,246.0,0.70,Helbutelj,Internationellt märke,Internationellt märke,Internationellt märke,NaN,NaN,115297.00,11,40.0
4,402,4,Kronvodka 40% 350 ml,Kronvodka,Altia,Sprit,Drinkar & Cocktails,VODKA,130.0,0.35,Halvbutelj,Internationellt märke,Internationellt märke,Internationellt märke,NaN,NaN,4436.60,12,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45876,60486703,604867,"Ability Shipping Starköl 5,5%","Ability Shipping Starköl 5,5%",Okänd producent,NaN,NaN,NaN,28.9,0.33,Flaska,NaN,NaN,NaN,NaN,NaN,79.20,51781636,5.5
45877,60498003,604980,"Ability Shipping Starköl 7,5%","Ability Shipping Starköl 7,5%",Okänd producent,NaN,NaN,NaN,29.9,0.33,Flaska,NaN,NaN,NaN,NaN,NaN,79.20,51781643,7.5
46184,60816001,608160,Ron Quorhum 30YO Anniversario 40%,Ron Quorhum 30YO Anniversario 40%,Okänd producent,NaN,NaN,NaN,999.0,0.70,Helbutelj,NaN,NaN,NaN,NaN,NaN,0.70,51875904,40.0
46380,60524802,605248,Het Snö (Spritglögg 35%vol),Het Snö (Spritglögg 35%vol),Okänd producent,NaN,NaN,NaN,278.0,0.50,Halvlitersbutelj,NaN,NaN,NaN,NaN,NaN,1.00,51883034,35.0
46400,8459801,84598,Daftmill Winter 2024 46% 700ml,Daftmill Winter Release 2024,Daftmill Distillery,Sprit,Whisky,MALTWHISKY,1722.0,0.70,Helbutelj,Storbritannien,Skottland,Lowlands,NaN,NaN,1.40,52033170,46.0

In [17]:
df["Mängd i 40 %"] = (df["Försäljning i liter"] * df["Alkoholhalt"] / 100) / 0.4
df

,Artnr,Varunr,Kvittonamn,Namn,Producentnamn,Varugrupp,Varugrupp detalj,Rubrik,Aktuellt pris,Volym i liter,Buteljtyp,Land,Region,Ursprung,Ekologisk,Etiskt,Försäljning i liter,Artikel ID,Alkoholhalt,Mängd i 40 %
0,101,1,"Renat 37,5% 700 ml",Renat,Pernod Ricard,Sprit,Drinkar & Cocktails,VODKA,215.0,0.70,Helbutelj,Sverige,Sverige,Sverige,NaN,NaN,180079.90,1,37.5,168824.906250
1,102,1,"Renat 37,5% 350 ml",Renat,Pernod Ricard,Sprit,Drinkar & Cocktails,VODKA,115.0,0.35,Halvbutelj,Internationellt märke,Internationellt märke,Internationellt märke,NaN,NaN,60997.30,2,37.5,57184.968750
2,302,3,"Explorer Vodka 37,5% 350 ml",Explorer Vodka,Altia Sweden AB,Sprit,Drinkar & Cocktails,VODKA,108.0,0.35,Halvbutelj,Internationellt märke,Internationellt märke,Internationellt märke,NaN,NaN,4.55,8,37.5,4.265625
3,401,4,Kronvodka 40% 700 ml,Kronvodka,Altia,Sprit,Drinkar & Cocktails,VODKA,246.0,0.70,Helbutelj,Internationellt märke,Internationellt märke,Internationellt märke,NaN,NaN,115297.00,11,40.0,115297.000000
4,402,4,Kronvodka 40% 350 ml,Kronvodka,Altia,Sprit,Drinkar & Cocktails,VODKA,130.0,0.35,Halvbutelj,Internationellt märke,Internationellt märke,Internationellt märke,NaN,NaN,4436.60,12,40.0,4436.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45876,60486703,604867,"Ability Shipping Starköl 5,5%","Ability Shipping Starköl 5,5%",Okänd producent,NaN,NaN,NaN,28.9,0.33,Flaska,NaN,NaN,NaN,NaN,NaN,79.20,51781636,5.5,10.890000
45877,60498003,604980,"Ability Shipping Starköl 7,5%","Ability Shipping Starköl 7,5%",Okänd producent,NaN,NaN,NaN,29.9,0.33,Flaska,NaN,NaN,NaN,NaN,NaN,79.20,51781643,7.5,14.850000
46184,60816001,608160,Ron Quorhum 30YO Anniversario 40%,Ron Quorhum 30YO Anniversario 40%,Okänd producent,NaN,NaN,NaN,999.0,0.70,Helbutelj,NaN,NaN,NaN,NaN,NaN,0.70,51875904,40.0,0.700000
46380,60524802,605248,Het Snö (Spritglögg 35%vol),Het Snö (Spritglögg 35%vol),Okänd producent,NaN,NaN,NaN,278.0,0.50,Halvlitersbutelj,NaN,NaN,NaN,NaN,NaN,1.00,51883034,35.0,0.875000
46400,8459801,84598,Daftmill Winter 2024 46% 700ml,Daftmill Winter Release 2024,Daftmill Distillery,Sprit,Whisky,MALTWHISKY,1722.0,0.70,Helbutelj,Storbritannien,Skottland,Lowlands,NaN,NaN,1.40,52033170,46.0,1.610000

In [ ]:
population_over_15 = 8.5e6
sum_of_liters = df["Mängd i 40 %"].sum()
res = sum_of_liters / population_over_15
res

# Officiella svaret är ca 8,4 liter 40 %-ig sprit per person
# ganska nära!

np.float64(7.872389968825558)

In [20]:
df["Alkohol per krona"] = (df["Volym i liter"] * df["Alkoholhalt"] / 100) / df["Aktuellt pris"]
df = df.sort_values("Alkohol per krona", ascending=False)
df

,Artnr,Varunr,Kvittonamn,Namn,Producentnamn,Varugrupp,Varugrupp detalj,Rubrik,Aktuellt pris,Volym i liter,...,Land,Region,Ursprung,Ekologisk,Etiskt,Försäljning i liter,Artikel ID,Alkoholhalt,Mängd i 40 %,Alkohol per krona
1679,1139212,11392,"Arboga 10,2% brk 500 ml","Arboga 10,2",Three Towns Ind Brewers,"Öl, cider & blanddryck",Lageröl,Lager > Ljus lager > Starkare lager,24.4,0.5,...,Sverige,Stockholms län,Stockholms stad,NaN,NaN,3316840.5,508393,10.2,8.457943e+05,2.090164e-03
1626,129612,1296,"Pripps Extra Stark 7,2% brk 500 ml",Pripps Extra Stark,Carlsberg Sverige AB,"Öl, cider & blanddryck",Lageröl,Lager > Ljus lager > Starkare lager,17.4,0.5,...,Sverige,Hallands län,Falkenbergs kommun,NaN,NaN,210.0,507799,7.2,3.780000e+01,2.068966e-03
1650,127312,1273,"Sofiero Guld 7,5% brk 500 ml",Sofiero Original Guld,Kopparbergs Bryggeri,"Öl, cider & blanddryck",Lageröl,Lager > Ljus lager > Starkare lager,18.5,0.5,...,Sverige,Sverige,Sverige,NaN,NaN,5582270.0,508019,7.5,1.046676e+06,2.027027e-03
1671,156812,1568,"Sju komma tvåan 7,2% brk 500 ml",Sju komma tvåan,Åbro Bryggeri,"Öl, cider & blanddryck",Lageröl,Lager > Ljus lager > Starkare lager,17.9,0.5,...,Sverige,Kalmar län,Vimmerby kommun,NaN,NaN,4089882.0,508323,7.2,7.361788e+05,2.011173e-03
1659,1122812,11228,"Three Hearts Extra Str 7,5% brk 500",Three Hearts Extra Strong,Krönleins,"Öl, cider & blanddryck",Lageröl,Lager > Ljus lager > Starkare lager,19.4,0.5,...,Sverige,Hallands län,Halmstads kommun,NaN,NaN,4497964.0,508176,7.5,8.433682e+05,1.932990e-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8647,1201201,12012,"Port Ellen 40th 50,9% 700ml",Port Ellen 40th,Port Ellen Distillery,Sprit,Whisky,MALTWHISKY,77990.0,0.7,...,Storbritannien,Skottland,Skottland,NaN,NaN,0.7,24479987,50.9,8.907500e-01,4.568534e-06
25243,4162401,41624,"Port Ellen 1981 42y 52,5% 700ml",Port Ellen Private Collection Sherry Butt 42 Y...,Gordon & MacPhail,Sprit,Whisky,MALTWHISKY,129950.0,0.7,...,Storbritannien,Skottland,Skottland,NaN,NaN,0.7,41723323,52.5,9.187500e-01,2.828011e-06
21529,9202501,92025,"The Macallan Fine & Ra 90 54,9%700",The Macallan Fine & Rare Cask #11233,The Edrington Group,Sprit,Whisky,MALTWHISKY,150000.0,0.7,...,Storbritannien,Skottland,Speyside,NaN,NaN,0.7,37415618,54.9,9.607500e-01,2.562000e-06
29479,4168201,41682,"The Macallan Tales of The 44,8% 700",The Macallan Tales of The Macallan Vol. II,The Edrington Group,Sprit,Whisky,MALTWHISKY,900000.0,0.7,...,Storbritannien,Skottland,Speyside,NaN,NaN,0.7,44037314,44.8,7.840000e-01,3.484444e-07
37574,8410101,84101,"Macallan Red Coll 60y 43,4% 700ml",The Macallan Red Collection 60 Years,The Edrington Group,Sprit,Whisky,MALTWHISKY,1280000.0,0.7,...,Storbritannien,Skottland,Highlands,NaN,NaN,0.7,47303722,43.4,7.595000e-01,2.373437e-07

In [23]:
# Mest alkohol för pengarna
df[["Kvittonamn", "Alkohol per krona", "Aktuellt pris"]].head(10)

                                Kvittonamn  Alkohol per krona  Aktuellt pris
1679               Arboga 10,2% brk 500 ml           0.002090           24.4
1626    Pripps Extra Stark 7,2% brk 500 ml           0.002069           17.4
1650          Sofiero Guld 7,5% brk 500 ml           0.002027           18.5
1671       Sju komma tvåan 7,2% brk 500 ml           0.002011           17.9
1659   Three Hearts Extra Str 7,5% brk 500           0.001933           19.4
20706   Pripps Extra Stark 6,8% brk 500 ml           0.001932           17.6
4526            APPELLO Aperitif 15% 750ml           0.001907           59.0
38454                   Snörsjö Lager 5,0%           0.001877          799.0
10027  Bira 91 Blonde Summer Lager4,5% 330           0.001854            8.9
23539     ALDO Casa Vinironia 13,5% Bib 3L           0.001849          219.0

In [24]:
# Minst alkohol för pengarna
df[["Kvittonamn", "Alkohol per krona", "Aktuellt pris"]].tail(10)

                                Kvittonamn  Alkohol per krona  Aktuellt pris
10481      Armagnac de Montal 1921 40% 700       8.128901e-06        34445.0
289      Rémy Martin Louis XIII 40% 700 ml       7.197943e-06        38900.0
3436           The Macallan No 6 43% 700ml       6.688889e-06        45000.0
21150   Macallan Double Cask 30y 43% 700ml       6.404255e-06        47000.0
38652     The Macallan Sh Oak 30 Y 43% 700       5.472727e-06        55000.0
8647           Port Ellen 40th 50,9% 700ml       4.568534e-06        77990.0
25243      Port Ellen 1981 42y 52,5% 700ml       2.828011e-06       129950.0
21529   The Macallan Fine & Ra 90 54,9%700       2.562000e-06       150000.0
29479  The Macallan Tales of The 44,8% 700       3.484444e-07       900000.0
37574    Macallan Red Coll 60y 43,4% 700ml       2.373437e-07      1280000.0